//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBAIGUIXE.Model
{
    using QLBAIGUIXE.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWPARKING: BaseViewModel
    {
        private string _LicensePlate { get; set; }
        public string LicensePlate { get => _LicensePlate; set { _LicensePlate = value; OnPropertyChanged(); } }
        private string _Code { get; set; }
        public string Code { get => _Code; set { _Code = value; OnPropertyChanged(); } }
    }
}
